[versions]
# Define the dependency versions
kotlin = "1.7.0"
androidGradlePlugin = "7.4.0"
compose = "1.2.0"
activityCompose = "1.3.1"


[libraries]
# Define the libraries
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }

[bundles]
# Define bundles/groups of libraries
compose = ["compose.ui", "compose.material", "compose.tooling"]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
